### ISSUE TITLE
[UI] Monospaced font for request body and response body

### ISSUE THREAD

**Issue by KaKi87** [fabiobento512/FRequest#19]

**Comment by fabiobento512** [comment]
Sorry for the delay in answering.

Thank you for your suggestion I have added courier new as new font for the request body and response body:
https://github.com/fabiobento512/FRequest/commit/2bd58a45d3f9b024f5e19bc69d426c808218a652

**Comment by KaKi87** [comment]
Must it be that one ? 😅

I would like to recommend those :

- [Inconsolata](https://fonts.google.com/specimen/Inconsolata)
- [Ubuntu Mono](https://fonts.google.com/specimen/Ubuntu+Mono)
- [Roboto Mono](https://fonts.google.com/specimen/Roboto+Mono)
- [Source Code Pro](https://fonts.google.com/specimen/Source+Code+Pro)

Thanks.

**Comment by fabiobento512** [comment]
For now it is easier because as far as I know courier new is one of the few monospaced fonts that are builtin in windows / macos / linux. Otherwise I would need to add the custom font to the build process.

Maybe I can make those customizable later? So any user could change it to their liking (including size). No promises though as I am working in the next release at the moment. If you want this, open a new issue/request for customizable fonts in the application.

**Comment by KaKi87** [comment]
Alright, done ! #21
